services:
  test-database:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DATABASE:-test_finances}
      POSTGRES_USER: ${POSTGRES_TEST_USER:-test_user}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-test_password}
    ports:
      - "${POSTGRES_TEST_PORT:-5437}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/test-data

volumes:
  pgdata:
