name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

jobs:
  # MAIN: check version → deploy
  check-version:
    if: "github.event.workflow_run.conclusion == 'success'"
    uses: ./.github/workflows/_check-version.yml

  deploy_to_ecr:
    needs: check-version
    uses: ./.github/workflows/_deploy-ecr.yml
    with:
      version: ${{ needs.check-version.outputs.version }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy_to_dockerhub:
    needs: check-version
    uses: ./.github/workflows/_deploy-dockerhub.yml
    with:
      version: ${{ needs.check-version.outputs.version }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
